language: python
python:
  - "3.6"

before_script:
  - pip install -r requirements.txt

  
services:
  - mongodb

# command to run tests
script:
  - nosetests -v --with-coverage --cover-package=app

after_success:
  - coveralls